Updated ruby version
This should fix the "gem install danger-gitlab" command, which was
returning:

ERROR:  Error installing danger-gitlab:
	There are no versions of octokit (~> 5.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	octokit requires Ruby version >= 2.7.0. The current ruby version is 2.5.9.229.